name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@main
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: no-jang
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Berlin
          plugin_achievements: yes
          plugin_activity: yes
          plugin_code: yes
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_lines: yes
          plugin_people: yes
          plugin_projects: yes
          plugin_traffic: yes
